# Generated by Django 5.0.2 on 2024-05-28 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_studentcourseerollment_enrolled_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='detail',
        ),
    ]
